<a href="https://colab.research.google.com/github/Bbarroo/Android_UI/blob/master/Numpy_100_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [4]:
import numpy as np

print(np.__version__)
np.show_config()

In [6]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
Z= np.zeros((10,10))
print(Z.size, Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

100 8
800 bytes


In [11]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [18]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [20]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
Z = np.random.random((3,3,3))
print(Z)
print(Z[1,1,2])

[[[0.47916571 0.52421969 0.10307279]
  [0.63633968 0.08963176 0.19413621]
  [0.80230222 0.45235622 0.71515254]]

 [[0.32488979 0.53920221 0.27482319]
  [0.56334529 0.31431101 0.55924819]
  [0.9966393  0.64365296 0.26108844]]

 [[0.44910641 0.19172161 0.92033912]
  [0.66107651 0.85911513 0.4958217 ]
  [0.82257168 0.61712771 0.07043167]]]
0.5592481941342599


In [23]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin,Zmax)

0.014989987985113196 0.9728825232242188


In [25]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4025323780372798


In [29]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [30]:
Z = np.ones((5,5))
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
Z = np.pad(Z, pad_width = 1, mode = 'constant', constant_values = 0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [36]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [37]:
Z = np.diag(1+np.arange(4), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [42]:
Z = np.ones((8,8))
Z[::2,::2] = 0
Z[1::2,1::2] = 0
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [45]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
[6]


In [52]:
z = np.array([[0,1],[1,0]])
Z = np.tile(z,(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [55]:
x = np.random.random((5,5))
normalize = (x-np.mean(x))/np.std(x)
print(normalize)

[[-1.44512331 -0.28620138  1.23255413  0.61764178  1.18686213]
 [-1.15289315 -1.23583548 -0.72165502 -1.15228342  1.04894795]
 [ 0.41928863 -0.10347989 -1.7307182   0.5331859   0.86252955]
 [ 1.1649413  -0.42554288 -1.5987511   1.25532769 -0.27825214]
 [ 0.86639092 -0.92638015 -0.17812552  1.12551579  0.9220559 ]]


In [57]:
a = np.random.random((5,3))
b = np.random.random((3,2))
Z = a@b
print(a)
print(b)
print(Z)

[[0.1924855  0.73822478 0.02884614]
 [0.61926106 0.39465013 0.9038363 ]
 [0.4615699  0.6249977  0.54642561]
 [0.41257529 0.69440589 0.0456961 ]
 [0.76311574 0.83704813 0.22415525]]
[[0.19368418 0.95983186]
 [0.48000307 0.26300323]
 [0.8784981  0.63652039]]
[[0.41697283 0.39727037]
 [1.10339282 1.273491  ]
 [0.86943347 0.95521695]
 [0.4533702  0.6077204 ]
 [0.74650908 1.09528855]]


In [60]:
Z = np.arange(15)
Z[(3<Z)&(Z<8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


In [62]:
print(np.sum(range(5),-1))

10


In [66]:
Z = np.random.choice(10,4)
print(Z)
print(Z**Z)
print(2<<Z>>2)
print ( Z <- Z)
print(1j*Z)
print(Z/1/1)

[5 0 8 6]
[    3125        1 16777216    46656]
[ 16   0 128  32]
[False False False False]
[0.+5.j 0.+0.j 0.+8.j 0.+6.j]
[5. 0. 8. 6.]
